export type MachineLanguage = "zh" | "en" | "es";

/* ═══════════════════════════════════════════
   Machine Cut Plan i18n lookup (independent of app locale)
   ═══════════════════════════════════════════ */
export const machineI18n: Record<string, Record<string, string>> = {
  zh: {
    tabLabel: "Visual Cut Plan",
    engineeringNo: "图纸",
    boardType: "板材型号",
    boardWidth: "宽度",
    totalLength: "总长度",
    trimSetting: "修边设置",
    sourceBoardCount: "板数",
    suggestedStack: "建议叠切",
    rowNo: "工程",
    cutLength: "裁切长度 (mm)",
    pieces: "件数",
    pieceCount: "片数",
    pieceCountHint: "表中为同一工程组内该裁切长度的总片数。",
    cutRowsMultiPatternHint: "本组含多种裁切组合，上表各行为全组合计。",
    perCutPieces: "片/刀",
    noStackReason: "各板裁切长度与片数组合不同，无法叠切；请分板按序加工。",
    widthRipBody:
      "板型原料宽约 {stock} mm，本工程条宽 {target} mm。除下表裁切长度方向下刀外，尚需纵裁（裁宽）至目标条宽；先长后宽或先宽后长由车间自定。",
    widthRipBadge: "需裁宽",
    notes: "备注",
    operatorNote1: "本工程组已匹配固定板材宽度，操作员只需输入裁切长度和数量。",
    operatorNote2: "上板 → 先修边 {trim}mm → 再按下表裁切。",
    printBtn: "打印",
    printTitle: "Visual Cut Plan",
    orderNo: "订单号",
    operator: "操作员",
    firstPieceCheck: "首件检查",
    completionCheck: "完工检查",
    printNotes: "备注",
    stackBatch: "批次",
    stackSize: "张/叠",
    stackBoards: "覆盖板数",
    stackSequence: "裁切顺序",
    stackSuggestions: "叠切建议",
    noData: "暂无裁切数据。",
    sheetsUnit: "张",
    mm: "mm",
    step1Title: "Step 1：机器设定",
    step1Desc1: "请确认板材型号为",
    step1Desc2: "在机器上输入总长度",
    step1Desc3: "，宽度",
    step1Desc4: "，修边设置",
    stepCutTitle: "Step {stepNum}：{patternNo}",
    stepCutDescFirst: "请取 {count} 张板材进行裁切。单次裁切数量已按单板生成（人工叠切时，机器端只需按此表输入，机器就会自动切出对应倍数的成品）：",
    stepCutDescNext: "请继续取 {count} 张板材进行 {patternNo} 的裁切。机器的总长度和宽度无需更改，请清除之前数据，重新从序号 1 开始输入：",
    boardWord: "板材",
    singleSheet: "1 张",
    stackBadge: "叠切 {n} 张",
    color: "颜色",
    t0RipTitle: "Step 1：T0 原板纵裁",
    t0RipDesc: "本图纸先从下列 T0 原板纵裁出对应条料；绿色为回收库存，斜纹为不可回收废料。",
    machineSetup: "机器设定",
    recovered: "回收",
    waste: "废料",
    fromLeft: "从左到右",
    phaseATitle: "T0 ➡️ T1",
    phaseBTitle: "T1 ➡️ T2",
    subStepSetup: "① 机器设定",
    subStepInput: "② 板材输入",
    subStepLayout: "③ 排版图",
    rawSheetWord: "原板",
    stripColumn: "条料",
    ripWidth: "纵裁宽度 (mm)",
  },
  en: {
    tabLabel: "Visual Cut Plan",
    engineeringNo: "Pattern",
    boardType: "Board Type",
    boardWidth: "Width",
    totalLength: "Total Length",
    trimSetting: "Trim Setting",
    sourceBoardCount: "Boards",
    suggestedStack: "Suggested Stack",
    rowNo: "Engineering",
    cutLength: "Cut Length (mm)",
    pieces: "Pieces",
    pieceCount: "Pieces",
    pieceCountHint: "Totals for this engineering group at each cut length.",
    cutRowsMultiPatternHint: "This group has multiple cut patterns; rows are combined totals.",
    perCutPieces: "pcs/cut",
    noStackReason: "Boards differ in cut lengths/counts — cannot stack; cut separately.",
    widthRipBody:
      "Nominal stock width ≈ {stock} mm, target strip {target} mm. Besides length cuts in the table, rip to strip width; cut order is shop-specific.",
    widthRipBadge: "Rip width",
    notes: "Notes",
    operatorNote1: "This engineering group uses a fixed board width. The operator only needs to input cut lengths and quantities.",
    operatorNote2: "Load board → Trim {trim}mm first → Then cut according to the table below.",
    printBtn: "Print",
    printTitle: "Visual Cut Plan",
    orderNo: "Order No.",
    operator: "Operator",
    firstPieceCheck: "First Piece Check",
    completionCheck: "Completion Check",
    printNotes: "Notes",
    stackBatch: "Batch",
    stackSize: "sheets/stack",
    stackBoards: "Covers Boards",
    stackSequence: "Cut Sequence",
    stackSuggestions: "Stack Suggestions",
    noData: "No cut data available.",
    sheetsUnit: "sheets",
    mm: "mm",
    step1Title: "Step 1: Machine Setup",
    step1Desc1: "Please confirm board type is",
    step1Desc2: "Input Total Length",
    step1Desc3: ", Width",
    step1Desc4: ", Trim Setting",
    stepCutTitle: "Step {stepNum}: {patternNo}",
    stepCutDescFirst: "Take {count} board(s) for cutting. Piece counts below are for a single board (if you stack boards manually, input these exact numbers into the machine):",
    stepCutDescNext: "Take the next {count} board(s) for {patternNo}. Total Length and Width do not need to be changed. Clear previous data and restart from Row 1:",
    boardWord: "Board",
    singleSheet: "1 Sheet",
    stackBadge: "Stack {n} sheets",
    color: "Color",
    t0RipTitle: "Step 1: T0 Raw Sheet Rip",
    t0RipDesc: "Rip the matching strips for this pattern from the T0 raw sheets below. Green is recovered stock; hatching is non-recoverable waste.",
    machineSetup: "Machine Setup",
    recovered: "Recovered",
    waste: "Waste",
    fromLeft: "Left to right",
    phaseATitle: "T0 ➡️ T1",
    phaseBTitle: "T1 ➡️ T2",
    subStepSetup: "① Machine Setup",
    subStepInput: "② Board Input",
    subStepLayout: "③ Layout",
    rawSheetWord: "Raw Sheet",
    stripColumn: "Strip",
    ripWidth: "Rip Width (mm)",
  },
  es: {
    tabLabel: "Visual Cut Plan",
    engineeringNo: "Patrón",
    boardType: "Tipo de Tablero",
    boardWidth: "Ancho",
    totalLength: "Longitud Total",
    trimSetting: "Ajuste de Recorte",
    sourceBoardCount: "Tableros",
    suggestedStack: "Apilado Sugerido",
    rowNo: "Ingeniería",
    cutLength: "Longitud de Corte (mm)",
    pieces: "Piezas",
    pieceCount: "Piezas",
    pieceCountHint: "Totales del grupo de ingeniería por longitud de corte.",
    cutRowsMultiPatternHint: "Varios patrones de corte en el grupo; la tabla muestra totales combinados.",
    perCutPieces: "pzs/corte",
    noStackReason: "Los tableros difieren en cortes — no apilar; cortar por separado.",
    widthRipBody:
      "Ancho nominal de stock ≈ {stock} mm, tira objetivo {target} mm. Además de los cortes en longitud, ripado al ancho de tira; el orden lo define el taller.",
    widthRipBadge: "Rip ancho",
    notes: "Notas",
    operatorNote1: "Este grupo de ingeniería usa un ancho fijo. El operador solo necesita ingresar longitudes y cantidades.",
    operatorNote2: "Cargar tablero → Recortar {trim}mm primero → Luego cortar según la tabla.",
    printBtn: "Imprimir",
    printTitle: "Visual Cut Plan",
    orderNo: "No. de Pedido",
    operator: "Operador",
    firstPieceCheck: "Verificación Primera Pieza",
    completionCheck: "Verificación Final",
    printNotes: "Notas",
    stackBatch: "Lote",
    stackSize: "hojas/pila",
    stackBoards: "Tableros Cubiertos",
    stackSequence: "Secuencia de Corte",
    stackSuggestions: "Sugerencias de Apilado",
    noData: "No hay datos de corte.",
    sheetsUnit: "hojas",
    mm: "mm",
    step1Title: "Paso 1: Configuración de Máquina",
    step1Desc1: "Confirme el tipo de tablero",
    step1Desc2: "Ingrese Longitud Total",
    step1Desc3: ", Ancho",
    step1Desc4: ", Ajuste Recorte",
    stepCutTitle: "Paso {stepNum}: {patternNo}",
    stepCutDescFirst: "Tome {count} tablero(s). Las cantidades son por tablero único (si apila, ingrese estos mismos números):",
    stepCutDescNext: "Tome {count} tablero(s) para {patternNo}. Longitud y Ancho no cambian. Limpie datos y reinicie de Fila 1:",
    boardWord: "Tablero",
    singleSheet: "1 Hoja",
    stackBadge: "Apilar {n} hojas",
    color: "Color",
    t0RipTitle: "Paso 1: Rip de Hoja T0",
    t0RipDesc: "Corte primero las tiras correspondientes de las hojas T0 abajo. Verde es material recuperado; rayado es desperdicio.",
    machineSetup: "Configuración de Máquina",
    recovered: "Recuperado",
    waste: "Desperdicio",
    fromLeft: "Izquierda a derecha",
    phaseATitle: "T0 ➡️ T1",
    phaseBTitle: "T1 ➡️ T2",
    subStepSetup: "① Configuración",
    subStepInput: "② Entrada de Tablero",
    subStepLayout: "③ Diagrama",
    rawSheetWord: "Hoja",
    stripColumn: "Tira",
    ripWidth: "Ancho de Corte (mm)",
  },
};

export const PRINT_FONT_STACK = [
  '"PingFang SC"',
  '"Hiragino Sans GB"',
  '"Microsoft YaHei"',
  '"Noto Sans CJK SC"',
  '"Noto Sans SC"',
  '"Source Han Sans SC"',
  '"Heiti SC"',
  '"SimHei"',
  '"WenQuanYi Micro Hei"',
  '-apple-system',
  "BlinkMacSystemFont",
  '"SF Pro Text"',
  '"Segoe UI"',
  '"Helvetica Neue"',
  "Arial",
  "sans-serif",
].join(", ");

